export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_MESSAGES = "GET_MESSAGES";
export const GET_CONTACTS = "GET_CONTACTS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";